# Site settings
title: Cody Planteen
email: planteen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a dump of my notes to the internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://planteen.github.io" # the base hostname & protocol for your site
github_username: planteen

# Build settings
markdown: kramdown
